# Generated by Django 4.1 on 2022-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suit',
            name='co',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suit',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suit',
            name='oxygen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
