# Generated by Django 4.1 on 2022-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_suit_co_suit_heart_rate_suit_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_suited',
            field=models.BooleanField(default=False),
        ),
    ]
