# Generated by Django 4.1 on 2022-08-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_suit_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suit',
            name='is_used',
        ),
    ]
