# Generated by Django 4.1 on 2022-08-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_id', models.CharField(max_length=10)),
                ('div', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='suit',
            name='suit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.available_suit'),
        ),
    ]
