# Generated by Django 4.1 on 2022-08-26 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_available_suit_alter_suit_suit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_suit',
            name='allocate_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
